### ISSUE TITLE
The HPSoftware organisation is being deprecated!

### ISSUE THREAD

**Issue by slbruce** [HPSoftware/ppm-versionone-connector#7]
The HPSoftware organisation is being deprecated and all active repositories should be moved to the [https://github.com/MicroFocus](Micro Focus) organisation.

After the 31st December 2017 this organisation and all its repositories will be locked and the HPSoftware organisation will be deleted.

For any questions please contact me or comment on this issue

**Comment by etiennec** [comment]
@slbruce any idea who can we contact on MicroFocus repo to get the right to create repositories?

**Comment by slbruce** [comment]
@etiennec I can do that for you.  Contact me through email and I can set you up

**Comment by etiennec** [comment]
@slbruce sure, but what's your MF email? Mine is etienne.canaud@microfocus.com

**Comment by etiennec** [comment]
Repo transfered to MicroFocus.
